/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Respuesta y puntaje otorgado por los usuarios a las preguntas SI o NO
 **/
@ApiModel(description = "Respuesta y puntaje otorgado por los usuarios a las preguntas SI o NO")
public class AnswerBooleanScore {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("campaign")
  private Campaign campaign = null;
  @SerializedName("headquarter")
  private Headquarter headquarter = null;
  @SerializedName("zone")
  private Zone zone = null;
  @SerializedName("questionItem")
  private QuestionItem questionItem = null;
  @SerializedName("meterDevice")
  private MeterDevice meterDevice = null;
  @SerializedName("cityCode")
  private Long cityCode = null;
  @SerializedName("cityName")
  private String cityName = null;
  @SerializedName("yesAnswer")
  private Integer yesAnswer = null;
  @SerializedName("noAnswer")
  private Integer noAnswer = null;
  @SerializedName("score")
  private Integer score = null;
  @SerializedName("registrationDate")
  private String registrationDate = null;
  @SerializedName("comment")
  private String comment = null;
  @SerializedName("userId")
  private String userId = null;

  /**
   * Identificador único de la respuesta
   **/
  @ApiModelProperty(value = "Identificador único de la respuesta")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Campaign getCampaign() {
    return campaign;
  }
  public void setCampaign(Campaign campaign) {
    this.campaign = campaign;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Headquarter getHeadquarter() {
    return headquarter;
  }
  public void setHeadquarter(Headquarter headquarter) {
    this.headquarter = headquarter;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Zone getZone() {
    return zone;
  }
  public void setZone(Zone zone) {
    this.zone = zone;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public QuestionItem getQuestionItem() {
    return questionItem;
  }
  public void setQuestionItem(QuestionItem questionItem) {
    this.questionItem = questionItem;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public MeterDevice getMeterDevice() {
    return meterDevice;
  }
  public void setMeterDevice(MeterDevice meterDevice) {
    this.meterDevice = meterDevice;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public Long getCityCode() {
    return cityCode;
  }
  public void setCityCode(Long cityCode) {
    this.cityCode = cityCode;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public String getCityName() {
    return cityName;
  }
  public void setCityName(String cityName) {
    this.cityName = cityName;
  }

  /**
   * Calificación posítiva
   **/
  @ApiModelProperty(value = "Calificación posítiva")
  public Integer getYesAnswer() {
    return yesAnswer;
  }
  public void setYesAnswer(Integer yesAnswer) {
    this.yesAnswer = yesAnswer;
  }

  /**
   * Calificación negátiva
   **/
  @ApiModelProperty(value = "Calificación negátiva")
  public Integer getNoAnswer() {
    return noAnswer;
  }
  public void setNoAnswer(Integer noAnswer) {
    this.noAnswer = noAnswer;
  }

  /**
   * Calificación total
   **/
  @ApiModelProperty(value = "Calificación total")
  public Integer getScore() {
    return score;
  }
  public void setScore(Integer score) {
    this.score = score;
  }

  /**
   * Fecha en que se realizó la calificación
   **/
  @ApiModelProperty(value = "Fecha en que se realizó la calificación")
  public String getRegistrationDate() {
    return registrationDate;
  }
  public void setRegistrationDate(String registrationDate) {
    this.registrationDate = registrationDate;
  }

  /**
   * Comentario del usuario
   **/
  @ApiModelProperty(value = "Comentario del usuario")
  public String getComment() {
    return comment;
  }
  public void setComment(String comment) {
    this.comment = comment;
  }

  /**
   * Identificación del usuario que califica
   **/
  @ApiModelProperty(value = "Identificación del usuario que califica")
  public String getUserId() {
    return userId;
  }
  public void setUserId(String userId) {
    this.userId = userId;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AnswerBooleanScore answerBooleanScore = (AnswerBooleanScore) o;
    return (this.id == null ? answerBooleanScore.id == null : this.id.equals(answerBooleanScore.id)) &&
        (this.campaign == null ? answerBooleanScore.campaign == null : this.campaign.equals(answerBooleanScore.campaign)) &&
        (this.headquarter == null ? answerBooleanScore.headquarter == null : this.headquarter.equals(answerBooleanScore.headquarter)) &&
        (this.zone == null ? answerBooleanScore.zone == null : this.zone.equals(answerBooleanScore.zone)) &&
        (this.questionItem == null ? answerBooleanScore.questionItem == null : this.questionItem.equals(answerBooleanScore.questionItem)) &&
        (this.meterDevice == null ? answerBooleanScore.meterDevice == null : this.meterDevice.equals(answerBooleanScore.meterDevice)) &&
        (this.cityCode == null ? answerBooleanScore.cityCode == null : this.cityCode.equals(answerBooleanScore.cityCode)) &&
        (this.cityName == null ? answerBooleanScore.cityName == null : this.cityName.equals(answerBooleanScore.cityName)) &&
        (this.yesAnswer == null ? answerBooleanScore.yesAnswer == null : this.yesAnswer.equals(answerBooleanScore.yesAnswer)) &&
        (this.noAnswer == null ? answerBooleanScore.noAnswer == null : this.noAnswer.equals(answerBooleanScore.noAnswer)) &&
        (this.score == null ? answerBooleanScore.score == null : this.score.equals(answerBooleanScore.score)) &&
        (this.registrationDate == null ? answerBooleanScore.registrationDate == null : this.registrationDate.equals(answerBooleanScore.registrationDate)) &&
        (this.comment == null ? answerBooleanScore.comment == null : this.comment.equals(answerBooleanScore.comment)) &&
        (this.userId == null ? answerBooleanScore.userId == null : this.userId.equals(answerBooleanScore.userId));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.campaign == null ? 0: this.campaign.hashCode());
    result = 31 * result + (this.headquarter == null ? 0: this.headquarter.hashCode());
    result = 31 * result + (this.zone == null ? 0: this.zone.hashCode());
    result = 31 * result + (this.questionItem == null ? 0: this.questionItem.hashCode());
    result = 31 * result + (this.meterDevice == null ? 0: this.meterDevice.hashCode());
    result = 31 * result + (this.cityCode == null ? 0: this.cityCode.hashCode());
    result = 31 * result + (this.cityName == null ? 0: this.cityName.hashCode());
    result = 31 * result + (this.yesAnswer == null ? 0: this.yesAnswer.hashCode());
    result = 31 * result + (this.noAnswer == null ? 0: this.noAnswer.hashCode());
    result = 31 * result + (this.score == null ? 0: this.score.hashCode());
    result = 31 * result + (this.registrationDate == null ? 0: this.registrationDate.hashCode());
    result = 31 * result + (this.comment == null ? 0: this.comment.hashCode());
    result = 31 * result + (this.userId == null ? 0: this.userId.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class AnswerBooleanScore {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  campaign: ").append(campaign).append("\n");
    sb.append("  headquarter: ").append(headquarter).append("\n");
    sb.append("  zone: ").append(zone).append("\n");
    sb.append("  questionItem: ").append(questionItem).append("\n");
    sb.append("  meterDevice: ").append(meterDevice).append("\n");
    sb.append("  cityCode: ").append(cityCode).append("\n");
    sb.append("  cityName: ").append(cityName).append("\n");
    sb.append("  yesAnswer: ").append(yesAnswer).append("\n");
    sb.append("  noAnswer: ").append(noAnswer).append("\n");
    sb.append("  score: ").append(score).append("\n");
    sb.append("  registrationDate: ").append(registrationDate).append("\n");
    sb.append("  comment: ").append(comment).append("\n");
    sb.append("  userId: ").append(userId).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
