/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Definición de las preguntas generales
 **/
@ApiModel(description = "Definición de las preguntas generales")
public class GeneralQuestionItem {
  
  @SerializedName("code")
  private Long code = null;
  @SerializedName("title")
  private String title = null;
  @SerializedName("description")
  private String description = null;
  @SerializedName("designOrder")
  private Integer designOrder = null;
  @SerializedName("designColor")
  private String designColor = null;
  @SerializedName("minScore")
  private Double minScore = null;
  @SerializedName("isPublished")
  private Boolean isPublished = null;
  @SerializedName("receiveComment")
  private Boolean receiveComment = null;
  @SerializedName("sendSmsNotification")
  private Boolean sendSmsNotification = null;

  /**
   * Identificador único de la pregunta
   **/
  @ApiModelProperty(value = "Identificador único de la pregunta")
  public Long getCode() {
    return code;
  }
  public void setCode(Long code) {
    this.code = code;
  }

  /**
   * Pregunta
   **/
  @ApiModelProperty(required = true, value = "Pregunta")
  public String getTitle() {
    return title;
  }
  public void setTitle(String title) {
    this.title = title;
  }

  /**
   * Descripción o soporte de ayuda a la pregunta
   **/
  @ApiModelProperty(value = "Descripción o soporte de ayuda a la pregunta")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }

  /**
   * Orden en que se listan las preguntas
   **/
  @ApiModelProperty(value = "Orden en que se listan las preguntas")
  public Integer getDesignOrder() {
    return designOrder;
  }
  public void setDesignOrder(Integer designOrder) {
    this.designOrder = designOrder;
  }

  /**
   * Color exadecimal de la pregunta
   **/
  @ApiModelProperty(value = "Color exadecimal de la pregunta")
  public String getDesignColor() {
    return designColor;
  }
  public void setDesignColor(String designColor) {
    this.designColor = designColor;
  }

  /**
   * Calificación mínima recidida por un usuario para generar alerta
   **/
  @ApiModelProperty(value = "Calificación mínima recidida por un usuario para generar alerta")
  public Double getMinScore() {
    return minScore;
  }
  public void setMinScore(Double minScore) {
    this.minScore = minScore;
  }

  /**
   * Encabezado activo o listo para visualizar
   **/
  @ApiModelProperty(value = "Encabezado activo o listo para visualizar")
  public Boolean getIsPublished() {
    return isPublished;
  }
  public void setIsPublished(Boolean isPublished) {
    this.isPublished = isPublished;
  }

  /**
   * Indica si la pregunta habilita comentario
   **/
  @ApiModelProperty(value = "Indica si la pregunta habilita comentario")
  public Boolean getReceiveComment() {
    return receiveComment;
  }
  public void setReceiveComment(Boolean receiveComment) {
    this.receiveComment = receiveComment;
  }

  /**
   * Indica la posibilidad de enviar notificación de Alerta SMS
   **/
  @ApiModelProperty(value = "Indica la posibilidad de enviar notificación de Alerta SMS")
  public Boolean getSendSmsNotification() {
    return sendSmsNotification;
  }
  public void setSendSmsNotification(Boolean sendSmsNotification) {
    this.sendSmsNotification = sendSmsNotification;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralQuestionItem generalQuestionItem = (GeneralQuestionItem) o;
    return (this.code == null ? generalQuestionItem.code == null : this.code.equals(generalQuestionItem.code)) &&
        (this.title == null ? generalQuestionItem.title == null : this.title.equals(generalQuestionItem.title)) &&
        (this.description == null ? generalQuestionItem.description == null : this.description.equals(generalQuestionItem.description)) &&
        (this.designOrder == null ? generalQuestionItem.designOrder == null : this.designOrder.equals(generalQuestionItem.designOrder)) &&
        (this.designColor == null ? generalQuestionItem.designColor == null : this.designColor.equals(generalQuestionItem.designColor)) &&
        (this.minScore == null ? generalQuestionItem.minScore == null : this.minScore.equals(generalQuestionItem.minScore)) &&
        (this.isPublished == null ? generalQuestionItem.isPublished == null : this.isPublished.equals(generalQuestionItem.isPublished)) &&
        (this.receiveComment == null ? generalQuestionItem.receiveComment == null : this.receiveComment.equals(generalQuestionItem.receiveComment)) &&
        (this.sendSmsNotification == null ? generalQuestionItem.sendSmsNotification == null : this.sendSmsNotification.equals(generalQuestionItem.sendSmsNotification));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.title == null ? 0: this.title.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    result = 31 * result + (this.designOrder == null ? 0: this.designOrder.hashCode());
    result = 31 * result + (this.designColor == null ? 0: this.designColor.hashCode());
    result = 31 * result + (this.minScore == null ? 0: this.minScore.hashCode());
    result = 31 * result + (this.isPublished == null ? 0: this.isPublished.hashCode());
    result = 31 * result + (this.receiveComment == null ? 0: this.receiveComment.hashCode());
    result = 31 * result + (this.sendSmsNotification == null ? 0: this.sendSmsNotification.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralQuestionItem {\n");
    
    sb.append("  code: ").append(code).append("\n");
    sb.append("  title: ").append(title).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("  designOrder: ").append(designOrder).append("\n");
    sb.append("  designColor: ").append(designColor).append("\n");
    sb.append("  minScore: ").append(minScore).append("\n");
    sb.append("  isPublished: ").append(isPublished).append("\n");
    sb.append("  receiveComment: ").append(receiveComment).append("\n");
    sb.append("  sendSmsNotification: ").append(sendSmsNotification).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
