/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Parametros generales de configuración
 **/
@ApiModel(description = "Parametros generales de configuración")
public class GeneralSettingParameter {
  
  @SerializedName("parameterKey")
  private String parameterKey = null;
  @SerializedName("parameterValue")
  private String parameterValue = null;

  /**
   * Llave que identifica el parámetro
   **/
  @ApiModelProperty(value = "Llave que identifica el parámetro")
  public String getParameterKey() {
    return parameterKey;
  }
  public void setParameterKey(String parameterKey) {
    this.parameterKey = parameterKey;
  }

  /**
   * Valor del parámetro
   **/
  @ApiModelProperty(value = "Valor del parámetro")
  public String getParameterValue() {
    return parameterValue;
  }
  public void setParameterValue(String parameterValue) {
    this.parameterValue = parameterValue;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    GeneralSettingParameter generalSettingParameter = (GeneralSettingParameter) o;
    return (this.parameterKey == null ? generalSettingParameter.parameterKey == null : this.parameterKey.equals(generalSettingParameter.parameterKey)) &&
        (this.parameterValue == null ? generalSettingParameter.parameterValue == null : this.parameterValue.equals(generalSettingParameter.parameterValue));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.parameterKey == null ? 0: this.parameterKey.hashCode());
    result = 31 * result + (this.parameterValue == null ? 0: this.parameterValue.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class GeneralSettingParameter {\n");
    
    sb.append("  parameterKey: ").append(parameterKey).append("\n");
    sb.append("  parameterValue: ").append(parameterValue).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
