/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class Logout {
  
  @SerializedName("userName")
  private String userName = null;
  @SerializedName("idPush")
  private String idPush = null;

  /**
   **/
  @ApiModelProperty(value = "")
  public String getUserName() {
    return userName;
  }
  public void setUserName(String userName) {
    this.userName = userName;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public String getIdPush() {
    return idPush;
  }
  public void setIdPush(String idPush) {
    this.idPush = idPush;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Logout logout = (Logout) o;
    return (this.userName == null ? logout.userName == null : this.userName.equals(logout.userName)) &&
        (this.idPush == null ? logout.idPush == null : this.idPush.equals(logout.idPush));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.userName == null ? 0: this.userName.hashCode());
    result = 31 * result + (this.idPush == null ? 0: this.idPush.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Logout {\n");
    
    sb.append("  userName: ").append(userName).append("\n");
    sb.append("  idPush: ").append(idPush).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
