/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Dispositivo medidor de campañas
 **/
@ApiModel(description = "Dispositivo medidor de campañas")
public class MeterDevice {
  
  @SerializedName("id")
  private Long id = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("deviceSerial")
  private String deviceSerial = null;
  @SerializedName("deviceVersionOs")
  private String deviceVersionOs = null;
  @SerializedName("deviceIdPush")
  private String deviceIdPush = null;
  @SerializedName("description")
  private String description = null;

  /**
   * Identificador único del medidor
   **/
  @ApiModelProperty(value = "Identificador único del medidor")
  public Long getId() {
    return id;
  }
  public void setId(Long id) {
    this.id = id;
  }

  /**
   * Nombre del medidor
   **/
  @ApiModelProperty(required = true, value = "Nombre del medidor")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   * Serial del dispositivo
   **/
  @ApiModelProperty(value = "Serial del dispositivo")
  public String getDeviceSerial() {
    return deviceSerial;
  }
  public void setDeviceSerial(String deviceSerial) {
    this.deviceSerial = deviceSerial;
  }

  /**
   * Versión del sistema operativo
   **/
  @ApiModelProperty(value = "Versión del sistema operativo")
  public String getDeviceVersionOs() {
    return deviceVersionOs;
  }
  public void setDeviceVersionOs(String deviceVersionOs) {
    this.deviceVersionOs = deviceVersionOs;
  }

  /**
   * Id push del dispositivo
   **/
  @ApiModelProperty(value = "Id push del dispositivo")
  public String getDeviceIdPush() {
    return deviceIdPush;
  }
  public void setDeviceIdPush(String deviceIdPush) {
    this.deviceIdPush = deviceIdPush;
  }

  /**
   * Descripción para identificar mejor el dispositivo
   **/
  @ApiModelProperty(value = "Descripción para identificar mejor el dispositivo")
  public String getDescription() {
    return description;
  }
  public void setDescription(String description) {
    this.description = description;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    MeterDevice meterDevice = (MeterDevice) o;
    return (this.id == null ? meterDevice.id == null : this.id.equals(meterDevice.id)) &&
        (this.name == null ? meterDevice.name == null : this.name.equals(meterDevice.name)) &&
        (this.deviceSerial == null ? meterDevice.deviceSerial == null : this.deviceSerial.equals(meterDevice.deviceSerial)) &&
        (this.deviceVersionOs == null ? meterDevice.deviceVersionOs == null : this.deviceVersionOs.equals(meterDevice.deviceVersionOs)) &&
        (this.deviceIdPush == null ? meterDevice.deviceIdPush == null : this.deviceIdPush.equals(meterDevice.deviceIdPush)) &&
        (this.description == null ? meterDevice.description == null : this.description.equals(meterDevice.description));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.id == null ? 0: this.id.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.deviceSerial == null ? 0: this.deviceSerial.hashCode());
    result = 31 * result + (this.deviceVersionOs == null ? 0: this.deviceVersionOs.hashCode());
    result = 31 * result + (this.deviceIdPush == null ? 0: this.deviceIdPush.hashCode());
    result = 31 * result + (this.description == null ? 0: this.description.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class MeterDevice {\n");
    
    sb.append("  id: ").append(id).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  deviceSerial: ").append(deviceSerial).append("\n");
    sb.append("  deviceVersionOs: ").append(deviceVersionOs).append("\n");
    sb.append("  deviceIdPush: ").append(deviceIdPush).append("\n");
    sb.append("  description: ").append(description).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
