/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

@ApiModel(description = "")
public class TargetZone {
  
  @SerializedName("zoneCode")
  private Long zoneCode = null;
  @SerializedName("campaignCode")
  private Long campaignCode = null;

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public Long getZoneCode() {
    return zoneCode;
  }
  public void setZoneCode(Long zoneCode) {
    this.zoneCode = zoneCode;
  }

  /**
   * 
   **/
  @ApiModelProperty(value = "")
  public Long getCampaignCode() {
    return campaignCode;
  }
  public void setCampaignCode(Long campaignCode) {
    this.campaignCode = campaignCode;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    TargetZone targetZone = (TargetZone) o;
    return (this.zoneCode == null ? targetZone.zoneCode == null : this.zoneCode.equals(targetZone.zoneCode)) &&
        (this.campaignCode == null ? targetZone.campaignCode == null : this.campaignCode.equals(targetZone.campaignCode));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.zoneCode == null ? 0: this.zoneCode.hashCode());
    result = 31 * result + (this.campaignCode == null ? 0: this.campaignCode.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class TargetZone {\n");
    
    sb.append("  zoneCode: ").append(zoneCode).append("\n");
    sb.append("  campaignCode: ").append(campaignCode).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
