/**
 * Smiller
 * Api de servicios REST para la aplicación [https://www.smilers.co](https://www.smilers.co).
 *
 * OpenAPI spec version: 1.0.0
 * Contact: apps@groupware.com.co
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

package co.smilers.model;

import io.swagger.annotations.*;
import com.google.gson.annotations.SerializedName;

/**
 * Zonas en las que se distrubuye una sede
 **/
@ApiModel(description = "Zonas en las que se distrubuye una sede")
public class Zone {
  
  @SerializedName("code")
  private Long code = null;
  @SerializedName("name")
  private String name = null;
  @SerializedName("headquarter")
  private Headquarter headquarter = null;
  @SerializedName("account")
  private String account = null;

  /**
   * Identificador único de la zona
   **/
  @ApiModelProperty(value = "Identificador único de la zona")
  public Long getCode() {
    return code;
  }
  public void setCode(Long code) {
    this.code = code;
  }

  /**
   * Nombre de la zona
   **/
  @ApiModelProperty(required = true, value = "Nombre de la zona")
  public String getName() {
    return name;
  }
  public void setName(String name) {
    this.name = name;
  }

  /**
   **/
  @ApiModelProperty(value = "")
  public Headquarter getHeadquarter() {
    return headquarter;
  }
  public void setHeadquarter(Headquarter headquarter) {
    this.headquarter = headquarter;
  }

  /**
   * Cuenta asociada a la zona
   **/
  @ApiModelProperty(value = "Cuenta asociada a la zona")
  public String getAccount() {
    return account;
  }
  public void setAccount(String account) {
    this.account = account;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Zone zone = (Zone) o;
    return (this.code == null ? zone.code == null : this.code.equals(zone.code)) &&
        (this.name == null ? zone.name == null : this.name.equals(zone.name)) &&
        (this.headquarter == null ? zone.headquarter == null : this.headquarter.equals(zone.headquarter)) &&
        (this.account == null ? zone.account == null : this.account.equals(zone.account));
  }

  @Override
  public int hashCode() {
    int result = 17;
    result = 31 * result + (this.code == null ? 0: this.code.hashCode());
    result = 31 * result + (this.name == null ? 0: this.name.hashCode());
    result = 31 * result + (this.headquarter == null ? 0: this.headquarter.hashCode());
    result = 31 * result + (this.account == null ? 0: this.account.hashCode());
    return result;
  }

  @Override
  public String toString()  {
    StringBuilder sb = new StringBuilder();
    sb.append("class Zone {\n");
    
    sb.append("  code: ").append(code).append("\n");
    sb.append("  name: ").append(name).append("\n");
    sb.append("  headquarter: ").append(headquarter).append("\n");
    sb.append("  account: ").append(account).append("\n");
    sb.append("}\n");
    return sb.toString();
  }
}
